apiVersion: v1
kind: ConfigMap
metadata:
  name: paypal-config
data:
  PORT: "8888"
  ACCOUNT_SERVICE_URL: http://account-service:8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-service-deployment
spec:
  selector:
    matchLabels:
      app: paypal-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: paypal-service-app
    spec:
      containers:
        - name: paypal-service-app
          image: greenex/paypal-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: paypal-config
---
apiVersion: v1
kind: Service
metadata:
  name: paypal-service
spec:
  type: LoadBalancer
  selector:
    app: paypal-service-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
