apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32003
  selector:
    app: mysql-db
  # clusterIp: none # uncomment if using ClusterIp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-db-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-db-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-db-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wltd/k8s-volumes/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS product;
        CREATE DATABASE IF NOT EXISTS `order`;
        CREATE DATABASE IF NOT EXISTS `account`;
        use product;
        CREATE TABLE IF NOT EXISTS `product` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` nvarchar(30) NOT NULL,
          `price` double NOT NULL,
          `quantity` int NOT NULL,
          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
        use `order`;
        CREATE TABLE IF NOT EXISTS `order` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `user_id` int(11) unsigned NOT NULL,
          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

        CREATE TABLE IF NOT EXISTS `order_products` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `product_id` int(11) unsigned NOT NULL,
          `order_id` int(11) unsigned NOT NULL,
          `qnt` int(11) unsigned NOT NULL,
          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
