apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  PORT: "1223"
  ACCOUNT_SERVICE_URL: http://account-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-deployment
spec:
  selector:
    matchLabels:
      app: shipping-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: shipping-service-app
    spec:
      containers:
        - name: shipping-service-app
          image: greenex/shipping-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 1223
          envFrom:
            - configMapRef:
                name: shipping-config
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: LoadBalancer
  selector:
    app: shipping-service-app
  ports:
    - protocol: TCP
      port: 1223
      targetPort: 1223
