apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  PORT: "7890"
  ACCOUNT_SERVICE_URL: http://account-service:8081
  ORDER_SERVICE_URL: http://order-service:3333
  CreditCard: http://credit-card-service:9999
  PayPal: http://paypal-service:8888

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
data:
  SALAH_SEC: U0FMQUhfU0VDUkVT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  selector:
    matchLabels:
      app: payment-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
        - name: payment-service-app
          image: greenex/payment-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 7890
          envFrom:
            - configMapRef:
                name: payment-config
            - secretRef:
                name: payment-secret

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: payment-service-app
  ports:
    - protocol: TCP
      port: 7890
      targetPort: 7890
