apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  PORT: "4444"
  DB_HOST: mysql-db
  DB_PORT: "3306"
  DB_USER: root
  DB_PASS: root
  DB_NAME: product
  PRODUCT_LIMIT: "30"
  STOCK_SERVICE_URL: http://socket-service
  ACCOUNT_SERVICE_URL: http://account-service
---
apiVersion: v1
kind: Secret
metadata:
  name: product-secret
data:
  SALAH_SEC: U0FMQUhfU0VDUkVT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  selector:
    matchLabels:
      app: product-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
        - name: product-service-app
          image: greenex/product-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
          envFrom:
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secret

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product-service-app
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
