apiVersion: v1
kind: Service
metadata:
  name: product-mysql-db
spec:
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32002
  selector:
    app: product-mysql-db
  # clusterIp: none # uncomment if using ClusterIp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: product-mysql-db
spec:
  selector:
    matchLabels:
      app: product-mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: product-mysql-db
    spec:
      containers:
        - image: mysql:5.6
          name: product-mysql-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: product-mysql-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: product-mysql-db-persistent-storage
          persistentVolumeClaim:
            claimName: product-mysql-db-pv-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: product-mysql-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wltd/k8s-volumes/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-mysql-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi