apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  PORT: "3333"
  DB_HOST: mysql-db
  DB_PORT: "3306"
  DB_USER: root
  DB_PASS: root
  DB_NAME: order
  ACCOUNT_SERVICE_URL: http://account-service
  PAYMENT_SERVICE_URL: http://payment-service
  SHIPPING_SERVICE_URL: http://shipping-service
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
data:
  SALAH_SEC: U0FMQUhfU0VDUkVT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  selector:
    matchLabels:
      app: order-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: greenex/order-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service-app
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
