apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-card-config
data:
  PORT: "9999"
  ACCOUNT_SERVICE_URL: http://account-service:8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-service-deployment
spec:
  selector:
    matchLabels:
      app: credit-card-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: credit-card-service-app
    spec:
      containers:
        - name: credit-card-service-app
          image: greenex/credit-card-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
          envFrom:
            - configMapRef:
                name: credit-card-config
---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-service
spec:
  type: LoadBalancer
  selector:
    app: credit-card-service-app
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
